export const NAME = "TradeX-Chart"
export const ID = "TradeXChart"

export const CLASS_DEFAULT   = "tradeXchart"
export const CLASS_UTILS     = "tradeXutils"
export const CLASS_BODY      = "tradeXbody"
export const CLASS_WIDGETSG  = "tradeXwidgetsG"
export const CLASS_TOOLS     = "tradeXtools"
export const CLASS_MAIN      = "tradeXmain"
export const CLASS_TIME      = "tradeXtime"
export const CLASS_ROWS      = "tradeXrow"
export const CLASS_ROW       = "tradeXrow"
export const CLASS_CHART     = "tradeXchart"
export const CLASS_SCALE     = "tradeXscale"
export const CLASS_WIDGETS   = "tradeXwidgets"
export const CLASS_ONCHART   = "tradeXonChart"
export const CLASS_OFFCHART  = "tradeXoffChart"