export const NAME = "TradeX-Chart"
export const ID = "TradeXChart"

export const CLASS_DEFAULT   = "tradeXchart"
export const CLASS_UTILS     = "tradeXutils"
export const CLASS_BODY      = "tradeXbody"
export const CLASS_WIDGETSG  = "tradeXwidgetsG"
export const CLASS_TOOLS     = "tradeXtools"
export const CLASS_MAIN      = "tradeXmain"
export const CLASS_TIME      = "tradeXtime"
export const CLASS_ROWS      = "tradeXrows"
export const CLASS_ROW       = "tradeXrow"
export const CLASS_CHART     = "tradeXchart"
export const CLASS_SCALE     = "tradeXscale"
export const CLASS_WIDGETS   = "tradeXwidgets"
export const CLASS_ONCHART   = "tradeXonChart"
export const CLASS_OFFCHART  = "tradeXoffChart"
export const CLASS_MENUS     = "tradeXmenus"
export const CLASS_MENU      = "tradeXmenu"
export const CLASS_DIVIDERS  = "tradeXdividers"
export const CLASS_WINDOW    = "tradeXwindow"
export const CLASS_PROGRESS  = "tradeXprogress"


export const RANGELIMIT = 500